name: quizzii
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/SourceSansPro-SemiBoldItalic.ttf
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/Lora-Regular.ttf
    - family: Dancing Script
      fonts:
        - asset: assets/DancingScript-Regular.ttf